# ---- build image ----
    FROM python:3.12-slim

    # Dependências do sistema que o psycopg2 precisa
    RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
    
    WORKDIR /app
    COPY backend/ /app
    
    RUN pip install --upgrade pip
    RUN pip install --no-cache-dir -r requirements.txt
    
    EXPOSE 8000
    CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    